on: [push, pull_request]
name: Cipher [test and build]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2-beta
      with:
        go-version: '1.14'
    - name: Checkout code
      uses: actions/checkout@v2-beta
    - name: Build
      - run: cd cipher && go build

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2-beta
      with:
        go-version: '1.14'
    - name: Checkout code
      uses: actions/checkout@v2-beta
    - name: Run tests
      - run: cd cipher && go test -v -covermode=count

  # coverage:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Install Go
  #     uses: actions/setup-go@v2-beta
  #     with:
  #       go-version: '1.14'
  #   - name: Checkout code
  #     uses: actions/checkout@v2-beta
  #   - name: Convert coverage to lcov
  #     uses: jandelgado/gcov2lcov-action@v1.0.0
  #     with:
  #         infile: cipher/coverage.out
  #         outfile: cipher_coverage.lcov
  #   - name: Coveralls
  #     uses: coverallsapp/github-action@v1.0.1
  #     with:
  #         github-token: ${{ secrets.github_token }}
  #         path-to-lcov: cipher_coverage.lcov