name: Cipher
on: [push]

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14'
      - run: cd cipher && go build
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14'
      - run: cd cipher && go test -v
