on: [push, pull_request]
name: Cipher
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2-beta
      with:
        go-version: '1.14'
    - name: Checkout code
      uses: actions/checkout@v2-beta
    - name: Build
      run: cd cipher && go build

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2-beta
      with:
        go-version: '1.14'
    - name: Checkout code
      uses: actions/checkout@v2-beta
    - name: Run tests
      run: cd cipher && go test -v -covermode=count

  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2-beta
      with:
        go-version: '1.14'
    - name: Checkout code
      uses: actions/checkout@v2-beta
    - name: Calc coverage 
      run: cd cipher && go test -v -covermode=count -coverprofile=../.coverage/cipher.out
    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.0
      with:
          infile: .coverage/cipher.out
          outfile: .coverage/cipher.lcov
    - name: Coveralls
      uses: coverallsapp/github-action@v1.0.1
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: .coverage/cipher.lcov