on: [push, pull_request]
name: Cipher
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2-beta
      with:
        go-version: '1.14'
    - name: Checkout code
      uses: actions/checkout@v2-beta
    - name: Build
      run: cd cli && go build

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2-beta
      with:
        go-version: '1.14'
    - name: Checkout code
      uses: actions/checkout@v2-beta
    - name: Run tests
      run: cd cli && go test -v -covermode=count
