name: Unit tests
on: [push]

jobs:
  - uses: actions/checkout@v2-beta
  - uses: actions/setup-go@v2-beta
    with:
      go-version: '1.14'
  build:
    name: Build source
    runs-on: ubuntu-latest
    steps:
      - run: go build
